### ISSUE TITLE
Potential deadlock

### ISSUE THREAD

**Issue by soruh** [withoutboats/ringbahn#6]
https://github.com/withoutboats/ringbahn/blob/5abaff63582f7380282a545371e2e10ad0b31402/src/driver.rs#L25

It seems to me like this line would deadlock, since the lock on `self.driver` is already held in `prepare`, but is also acquired in`self.submit`.

**Comment by withoutboats** [comment]
You're right, the code should be changed to `driver.submit()`!

**Comment by withoutboats** [comment]
Thanks all fixed!
